//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_Banco.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Banco">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="002"/>
 *     &lt;enumeration value="006"/>
 *     &lt;enumeration value="009"/>
 *     &lt;enumeration value="012"/>
 *     &lt;enumeration value="014"/>
 *     &lt;enumeration value="019"/>
 *     &lt;enumeration value="021"/>
 *     &lt;enumeration value="030"/>
 *     &lt;enumeration value="032"/>
 *     &lt;enumeration value="036"/>
 *     &lt;enumeration value="037"/>
 *     &lt;enumeration value="042"/>
 *     &lt;enumeration value="044"/>
 *     &lt;enumeration value="058"/>
 *     &lt;enumeration value="059"/>
 *     &lt;enumeration value="060"/>
 *     &lt;enumeration value="062"/>
 *     &lt;enumeration value="072"/>
 *     &lt;enumeration value="102"/>
 *     &lt;enumeration value="103"/>
 *     &lt;enumeration value="106"/>
 *     &lt;enumeration value="108"/>
 *     &lt;enumeration value="110"/>
 *     &lt;enumeration value="112"/>
 *     &lt;enumeration value="113"/>
 *     &lt;enumeration value="116"/>
 *     &lt;enumeration value="124"/>
 *     &lt;enumeration value="126"/>
 *     &lt;enumeration value="127"/>
 *     &lt;enumeration value="128"/>
 *     &lt;enumeration value="129"/>
 *     &lt;enumeration value="130"/>
 *     &lt;enumeration value="131"/>
 *     &lt;enumeration value="132"/>
 *     &lt;enumeration value="133"/>
 *     &lt;enumeration value="134"/>
 *     &lt;enumeration value="135"/>
 *     &lt;enumeration value="136"/>
 *     &lt;enumeration value="137"/>
 *     &lt;enumeration value="138"/>
 *     &lt;enumeration value="139"/>
 *     &lt;enumeration value="140"/>
 *     &lt;enumeration value="141"/>
 *     &lt;enumeration value="143"/>
 *     &lt;enumeration value="145"/>
 *     &lt;enumeration value="166"/>
 *     &lt;enumeration value="168"/>
 *     &lt;enumeration value="600"/>
 *     &lt;enumeration value="601"/>
 *     &lt;enumeration value="602"/>
 *     &lt;enumeration value="605"/>
 *     &lt;enumeration value="606"/>
 *     &lt;enumeration value="607"/>
 *     &lt;enumeration value="608"/>
 *     &lt;enumeration value="610"/>
 *     &lt;enumeration value="614"/>
 *     &lt;enumeration value="615"/>
 *     &lt;enumeration value="616"/>
 *     &lt;enumeration value="617"/>
 *     &lt;enumeration value="618"/>
 *     &lt;enumeration value="619"/>
 *     &lt;enumeration value="620"/>
 *     &lt;enumeration value="621"/>
 *     &lt;enumeration value="622"/>
 *     &lt;enumeration value="623"/>
 *     &lt;enumeration value="626"/>
 *     &lt;enumeration value="627"/>
 *     &lt;enumeration value="628"/>
 *     &lt;enumeration value="629"/>
 *     &lt;enumeration value="630"/>
 *     &lt;enumeration value="631"/>
 *     &lt;enumeration value="632"/>
 *     &lt;enumeration value="633"/>
 *     &lt;enumeration value="634"/>
 *     &lt;enumeration value="636"/>
 *     &lt;enumeration value="637"/>
 *     &lt;enumeration value="638"/>
 *     &lt;enumeration value="640"/>
 *     &lt;enumeration value="642"/>
 *     &lt;enumeration value="646"/>
 *     &lt;enumeration value="647"/>
 *     &lt;enumeration value="648"/>
 *     &lt;enumeration value="649"/>
 *     &lt;enumeration value="651"/>
 *     &lt;enumeration value="652"/>
 *     &lt;enumeration value="653"/>
 *     &lt;enumeration value="655"/>
 *     &lt;enumeration value="656"/>
 *     &lt;enumeration value="659"/>
 *     &lt;enumeration value="901"/>
 *     &lt;enumeration value="902"/>
 *     &lt;enumeration value="670"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_Banco", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_Banco {

    @XmlEnumValue("002")
    VALUE_1("002"),
    @XmlEnumValue("006")
    VALUE_2("006"),
    @XmlEnumValue("009")
    VALUE_3("009"),
    @XmlEnumValue("012")
    VALUE_4("012"),
    @XmlEnumValue("014")
    VALUE_5("014"),
    @XmlEnumValue("019")
    VALUE_6("019"),
    @XmlEnumValue("021")
    VALUE_7("021"),
    @XmlEnumValue("030")
    VALUE_8("030"),
    @XmlEnumValue("032")
    VALUE_9("032"),
    @XmlEnumValue("036")
    VALUE_10("036"),
    @XmlEnumValue("037")
    VALUE_11("037"),
    @XmlEnumValue("042")
    VALUE_12("042"),
    @XmlEnumValue("044")
    VALUE_13("044"),
    @XmlEnumValue("058")
    VALUE_14("058"),
    @XmlEnumValue("059")
    VALUE_15("059"),
    @XmlEnumValue("060")
    VALUE_16("060"),
    @XmlEnumValue("062")
    VALUE_17("062"),
    @XmlEnumValue("072")
    VALUE_18("072"),
    @XmlEnumValue("102")
    VALUE_19("102"),
    @XmlEnumValue("103")
    VALUE_20("103"),
    @XmlEnumValue("106")
    VALUE_21("106"),
    @XmlEnumValue("108")
    VALUE_22("108"),
    @XmlEnumValue("110")
    VALUE_23("110"),
    @XmlEnumValue("112")
    VALUE_24("112"),
    @XmlEnumValue("113")
    VALUE_25("113"),
    @XmlEnumValue("116")
    VALUE_26("116"),
    @XmlEnumValue("124")
    VALUE_27("124"),
    @XmlEnumValue("126")
    VALUE_28("126"),
    @XmlEnumValue("127")
    VALUE_29("127"),
    @XmlEnumValue("128")
    VALUE_30("128"),
    @XmlEnumValue("129")
    VALUE_31("129"),
    @XmlEnumValue("130")
    VALUE_32("130"),
    @XmlEnumValue("131")
    VALUE_33("131"),
    @XmlEnumValue("132")
    VALUE_34("132"),
    @XmlEnumValue("133")
    VALUE_35("133"),
    @XmlEnumValue("134")
    VALUE_36("134"),
    @XmlEnumValue("135")
    VALUE_37("135"),
    @XmlEnumValue("136")
    VALUE_38("136"),
    @XmlEnumValue("137")
    VALUE_39("137"),
    @XmlEnumValue("138")
    VALUE_40("138"),
    @XmlEnumValue("139")
    VALUE_41("139"),
    @XmlEnumValue("140")
    VALUE_42("140"),
    @XmlEnumValue("141")
    VALUE_43("141"),
    @XmlEnumValue("143")
    VALUE_44("143"),
    @XmlEnumValue("145")
    VALUE_45("145"),
    @XmlEnumValue("166")
    VALUE_46("166"),
    @XmlEnumValue("168")
    VALUE_47("168"),
    @XmlEnumValue("600")
    VALUE_48("600"),
    @XmlEnumValue("601")
    VALUE_49("601"),
    @XmlEnumValue("602")
    VALUE_50("602"),
    @XmlEnumValue("605")
    VALUE_51("605"),
    @XmlEnumValue("606")
    VALUE_52("606"),
    @XmlEnumValue("607")
    VALUE_53("607"),
    @XmlEnumValue("608")
    VALUE_54("608"),
    @XmlEnumValue("610")
    VALUE_55("610"),
    @XmlEnumValue("614")
    VALUE_56("614"),
    @XmlEnumValue("615")
    VALUE_57("615"),
    @XmlEnumValue("616")
    VALUE_58("616"),
    @XmlEnumValue("617")
    VALUE_59("617"),
    @XmlEnumValue("618")
    VALUE_60("618"),
    @XmlEnumValue("619")
    VALUE_61("619"),
    @XmlEnumValue("620")
    VALUE_62("620"),
    @XmlEnumValue("621")
    VALUE_63("621"),
    @XmlEnumValue("622")
    VALUE_64("622"),
    @XmlEnumValue("623")
    VALUE_65("623"),
    @XmlEnumValue("626")
    VALUE_66("626"),
    @XmlEnumValue("627")
    VALUE_67("627"),
    @XmlEnumValue("628")
    VALUE_68("628"),
    @XmlEnumValue("629")
    VALUE_69("629"),
    @XmlEnumValue("630")
    VALUE_70("630"),
    @XmlEnumValue("631")
    VALUE_71("631"),
    @XmlEnumValue("632")
    VALUE_72("632"),
    @XmlEnumValue("633")
    VALUE_73("633"),
    @XmlEnumValue("634")
    VALUE_74("634"),
    @XmlEnumValue("636")
    VALUE_75("636"),
    @XmlEnumValue("637")
    VALUE_76("637"),
    @XmlEnumValue("638")
    VALUE_77("638"),
    @XmlEnumValue("640")
    VALUE_78("640"),
    @XmlEnumValue("642")
    VALUE_79("642"),
    @XmlEnumValue("646")
    VALUE_80("646"),
    @XmlEnumValue("647")
    VALUE_81("647"),
    @XmlEnumValue("648")
    VALUE_82("648"),
    @XmlEnumValue("649")
    VALUE_83("649"),
    @XmlEnumValue("651")
    VALUE_84("651"),
    @XmlEnumValue("652")
    VALUE_85("652"),
    @XmlEnumValue("653")
    VALUE_86("653"),
    @XmlEnumValue("655")
    VALUE_87("655"),
    @XmlEnumValue("656")
    VALUE_88("656"),
    @XmlEnumValue("659")
    VALUE_89("659"),
    @XmlEnumValue("901")
    VALUE_90("901"),
    @XmlEnumValue("902")
    VALUE_91("902"),
    @XmlEnumValue("670")
    VALUE_92("670");
    private final String value;

    C_Banco(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_Banco fromValue(String v) {
        for (C_Banco c: C_Banco.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
