//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_PeriodicidadPago.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_PeriodicidadPago">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="09"/>
 *     &lt;enumeration value="10"/>
 *     &lt;enumeration value="99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_PeriodicidadPago", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_PeriodicidadPago {

	/** 01 - Diario */
    @XmlEnumValue("01")
    VALUE_1("01"),
    
    /** 02 - Semanal */
    @XmlEnumValue("02")
    VALUE_2("02"),
    
    /** 03 - Catorcenal */
    @XmlEnumValue("03")
    VALUE_3("03"),
    
    /** 04 - Quincenal */
    @XmlEnumValue("04")
    VALUE_4("04"),
    
    /** 05 - Mensual */
    @XmlEnumValue("05")
    VALUE_5("05"),
    
    /** 06 - Bimestral */
    @XmlEnumValue("06")
    VALUE_6("06"),
    
    /** 07 - Unidad obra */
    @XmlEnumValue("07")
    VALUE_7("07"),
    
    /** 08 - Comisi&oacute;n */
    @XmlEnumValue("08")
    VALUE_8("08"),
    
    /** 09 - Precio alzado */
    @XmlEnumValue("09")
    VALUE_9("09"),
    
    /** 10 - Decenal */
    @XmlEnumValue("10")
    VALUE_10("10"),
    
    /** 99 - Otra Periodicidad */
    @XmlEnumValue("99")
    VALUE_11("99");
    private final String value;

    C_PeriodicidadPago(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_PeriodicidadPago fromValue(String v) {
        for (C_PeriodicidadPago c: C_PeriodicidadPago.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
