//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_RiesgoPuesto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_RiesgoPuesto">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="2"/>
 *     &lt;enumeration value="3"/>
 *     &lt;enumeration value="4"/>
 *     &lt;enumeration value="5"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_RiesgoPuesto", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_RiesgoPuesto {

	/** 1 - Clase I*/
    @XmlEnumValue("1")
    VALUE_1("1"),
    
    /** 2 - Clase II*/
    @XmlEnumValue("2")
    VALUE_2("2"),
    
    /** 3 - Clase III*/
    @XmlEnumValue("3")
    VALUE_3("3"),
    
    /** 4 - Clase IV*/
    @XmlEnumValue("4")
    VALUE_4("4"),
    
    /** 5 - Clase V*/
    @XmlEnumValue("5")
    VALUE_5("5");
    private final String value;

    C_RiesgoPuesto(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_RiesgoPuesto fromValue(String v) {
        for (C_RiesgoPuesto c: C_RiesgoPuesto.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
