//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoPercepcion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoPercepcion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="001"/>
 *     &lt;enumeration value="002"/>
 *     &lt;enumeration value="003"/>
 *     &lt;enumeration value="004"/>
 *     &lt;enumeration value="005"/>
 *     &lt;enumeration value="006"/>
 *     &lt;enumeration value="009"/>
 *     &lt;enumeration value="010"/>
 *     &lt;enumeration value="011"/>
 *     &lt;enumeration value="012"/>
 *     &lt;enumeration value="013"/>
 *     &lt;enumeration value="014"/>
 *     &lt;enumeration value="015"/>
 *     &lt;enumeration value="019"/>
 *     &lt;enumeration value="020"/>
 *     &lt;enumeration value="021"/>
 *     &lt;enumeration value="022"/>
 *     &lt;enumeration value="023"/>
 *     &lt;enumeration value="024"/>
 *     &lt;enumeration value="025"/>
 *     &lt;enumeration value="026"/>
 *     &lt;enumeration value="027"/>
 *     &lt;enumeration value="028"/>
 *     &lt;enumeration value="029"/>
 *     &lt;enumeration value="030"/>
 *     &lt;enumeration value="031"/>
 *     &lt;enumeration value="032"/>
 *     &lt;enumeration value="033"/>
 *     &lt;enumeration value="034"/>
 *     &lt;enumeration value="035"/>
 *     &lt;enumeration value="036"/>
 *     &lt;enumeration value="037"/>
 *     &lt;enumeration value="038"/>
 *     &lt;enumeration value="039"/>
 *     &lt;enumeration value="044"/>
 *     &lt;enumeration value="045"/>
 *     &lt;enumeration value="046"/>
 *     &lt;enumeration value="047"/>
 *     &lt;enumeration value="048"/>
 *     &lt;enumeration value="049"/>
 *     &lt;enumeration value="050"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoPercepcion", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoPercepcion {

    @XmlEnumValue("001")
    VALUE_1("001"),
    @XmlEnumValue("002")
    VALUE_2("002"),
    @XmlEnumValue("003")
    VALUE_3("003"),
    @XmlEnumValue("004")
    VALUE_4("004"),
    @XmlEnumValue("005")
    VALUE_5("005"),
    @XmlEnumValue("006")
    VALUE_6("006"),
    @XmlEnumValue("009")
    VALUE_7("009"),
    @XmlEnumValue("010")
    VALUE_8("010"),
    @XmlEnumValue("011")
    VALUE_9("011"),
    @XmlEnumValue("012")
    VALUE_10("012"),
    @XmlEnumValue("013")
    VALUE_11("013"),
    @XmlEnumValue("014")
    VALUE_12("014"),
    @XmlEnumValue("015")
    VALUE_13("015"),
    @XmlEnumValue("019")
    VALUE_14("019"),
    @XmlEnumValue("020")
    VALUE_15("020"),
    @XmlEnumValue("021")
    VALUE_16("021"),
    @XmlEnumValue("022")
    VALUE_17("022"),
    @XmlEnumValue("023")
    VALUE_18("023"),
    @XmlEnumValue("024")
    VALUE_19("024"),
    @XmlEnumValue("025")
    VALUE_20("025"),
    @XmlEnumValue("026")
    VALUE_21("026"),
    @XmlEnumValue("027")
    VALUE_22("027"),
    @XmlEnumValue("028")
    VALUE_23("028"),
    @XmlEnumValue("029")
    VALUE_24("029"),
    @XmlEnumValue("030")
    VALUE_25("030"),
    @XmlEnumValue("031")
    VALUE_26("031"),
    @XmlEnumValue("032")
    VALUE_27("032"),
    @XmlEnumValue("033")
    VALUE_28("033"),
    @XmlEnumValue("034")
    VALUE_29("034"),
    @XmlEnumValue("035")
    VALUE_30("035"),
    @XmlEnumValue("036")
    VALUE_31("036"),
    @XmlEnumValue("037")
    VALUE_32("037"),
    @XmlEnumValue("038")
    VALUE_33("038"),
    @XmlEnumValue("039")
    VALUE_34("039"),
    @XmlEnumValue("044")
    VALUE_35("044"),
    @XmlEnumValue("045")
    VALUE_36("045"),
    @XmlEnumValue("046")
    VALUE_37("046"),
    @XmlEnumValue("047")
    VALUE_38("047"),
    @XmlEnumValue("048")
    VALUE_39("048"),
    @XmlEnumValue("049")
    VALUE_40("049"),
    @XmlEnumValue("050")
    VALUE_41("050");
    private final String value;

    C_TipoPercepcion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoPercepcion fromValue(String v) {
        for (C_TipoPercepcion c: C_TipoPercepcion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
