//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoContrato.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoContrato">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="09"/>
 *     &lt;enumeration value="10"/>
 *     &lt;enumeration value="99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoContrato", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoContrato {

	/** 01 - Contrato de trabajo por tiempo indeterminado */
    @XmlEnumValue("01")
    VALUE_1("01"),
    
    /** 01 - Contrato de trabajo para obra determinada */
    @XmlEnumValue("02")
    VALUE_2("02"),
    
    /** 01 - Contrato de trabajo por tiempo determinado */
    @XmlEnumValue("03")
    VALUE_3("03"),
    
    /** 01 - Contrato de trabajo por temporada */
    @XmlEnumValue("04")
    VALUE_4("04"),
    
    /** 01 - Contrato de trabajo sujeto a prueba */
    @XmlEnumValue("05")
    VALUE_5("05"),
    
    /** 01 - Contrato de trabajo con capacitaci&oacute;n inicial */
    @XmlEnumValue("06")
    VALUE_6("06"),
    
    /** 01 - Modalidad de contrataci&oacute;n por pago de hora laborada */
    @XmlEnumValue("07")
    VALUE_7("07"),
    
    /** 01 - Modalidad de trabajo por comisi&oacute;n laboral */
    @XmlEnumValue("08")
    VALUE_8("08"),
    
    /** 01 - Modalidades de contrataci&oacute;n donde no existe relaci&oacute;n de trabajo */
    @XmlEnumValue("09")
    VALUE_9("09"),
    
    /** 01 - Jubilaci&oacute;n, pensi&oacute;n, retiro. */
    @XmlEnumValue("10")
    VALUE_10("10"),
    
    /** 01 - Otro contrato */
    @XmlEnumValue("99")
    VALUE_11("99");
    
    private final String value;

    C_TipoContrato(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoContrato fromValue(String v) {
        for (C_TipoContrato c: C_TipoContrato.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
