//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoHoras.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoHoras">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoHoras", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoHoras {

	/** 01 - Dobles */
    @XmlEnumValue("01")
    VALUE_1("01"),
    /** 02 - Triples */
    @XmlEnumValue("02")
    VALUE_2("02"),
    /** 03 - Simples */
    @XmlEnumValue("03")
    VALUE_3("03");
    private final String value;

    C_TipoHoras(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoHoras fromValue(String v) {
        for (C_TipoHoras c: C_TipoHoras.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
