//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoDeduccion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoDeduccion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="001"/>
 *     &lt;enumeration value="002"/>
 *     &lt;enumeration value="003"/>
 *     &lt;enumeration value="004"/>
 *     &lt;enumeration value="005"/>
 *     &lt;enumeration value="006"/>
 *     &lt;enumeration value="007"/>
 *     &lt;enumeration value="008"/>
 *     &lt;enumeration value="009"/>
 *     &lt;enumeration value="010"/>
 *     &lt;enumeration value="011"/>
 *     &lt;enumeration value="012"/>
 *     &lt;enumeration value="013"/>
 *     &lt;enumeration value="014"/>
 *     &lt;enumeration value="015"/>
 *     &lt;enumeration value="016"/>
 *     &lt;enumeration value="017"/>
 *     &lt;enumeration value="018"/>
 *     &lt;enumeration value="019"/>
 *     &lt;enumeration value="020"/>
 *     &lt;enumeration value="021"/>
 *     &lt;enumeration value="022"/>
 *     &lt;enumeration value="023"/>
 *     &lt;enumeration value="024"/>
 *     &lt;enumeration value="025"/>
 *     &lt;enumeration value="026"/>
 *     &lt;enumeration value="027"/>
 *     &lt;enumeration value="028"/>
 *     &lt;enumeration value="029"/>
 *     &lt;enumeration value="030"/>
 *     &lt;enumeration value="031"/>
 *     &lt;enumeration value="032"/>
 *     &lt;enumeration value="033"/>
 *     &lt;enumeration value="034"/>
 *     &lt;enumeration value="035"/>
 *     &lt;enumeration value="036"/>
 *     &lt;enumeration value="037"/>
 *     &lt;enumeration value="038"/>
 *     &lt;enumeration value="039"/>
 *     &lt;enumeration value="040"/>
 *     &lt;enumeration value="041"/>
 *     &lt;enumeration value="042"/>
 *     &lt;enumeration value="043"/>
 *     &lt;enumeration value="044"/>
 *     &lt;enumeration value="045"/>
 *     &lt;enumeration value="046"/>
 *     &lt;enumeration value="047"/>
 *     &lt;enumeration value="048"/>
 *     &lt;enumeration value="049"/>
 *     &lt;enumeration value="050"/>
 *     &lt;enumeration value="051"/>
 *     &lt;enumeration value="052"/>
 *     &lt;enumeration value="053"/>
 *     &lt;enumeration value="054"/>
 *     &lt;enumeration value="055"/>
 *     &lt;enumeration value="056"/>
 *     &lt;enumeration value="057"/>
 *     &lt;enumeration value="058"/>
 *     &lt;enumeration value="059"/>
 *     &lt;enumeration value="060"/>
 *     &lt;enumeration value="061"/>
 *     &lt;enumeration value="062"/>
 *     &lt;enumeration value="063"/>
 *     &lt;enumeration value="064"/>
 *     &lt;enumeration value="065"/>
 *     &lt;enumeration value="066"/>
 *     &lt;enumeration value="067"/>
 *     &lt;enumeration value="068"/>
 *     &lt;enumeration value="069"/>
 *     &lt;enumeration value="070"/>
 *     &lt;enumeration value="071"/>
 *     &lt;enumeration value="072"/>
 *     &lt;enumeration value="073"/>
 *     &lt;enumeration value="074"/>
 *     &lt;enumeration value="075"/>
 *     &lt;enumeration value="076"/>
 *     &lt;enumeration value="077"/>
 *     &lt;enumeration value="078"/>
 *     &lt;enumeration value="079"/>
 *     &lt;enumeration value="080"/>
 *     &lt;enumeration value="081"/>
 *     &lt;enumeration value="082"/>
 *     &lt;enumeration value="083"/>
 *     &lt;enumeration value="084"/>
 *     &lt;enumeration value="085"/>
 *     &lt;enumeration value="086"/>
 *     &lt;enumeration value="087"/>
 *     &lt;enumeration value="088"/>
 *     &lt;enumeration value="089"/>
 *     &lt;enumeration value="090"/>
 *     &lt;enumeration value="091"/>
 *     &lt;enumeration value="092"/>
 *     &lt;enumeration value="093"/>
 *     &lt;enumeration value="094"/>
 *     &lt;enumeration value="095"/>
 *     &lt;enumeration value="096"/>
 *     &lt;enumeration value="097"/>
 *     &lt;enumeration value="098"/>
 *     &lt;enumeration value="099"/>
 *     &lt;enumeration value="100"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoDeduccion", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoDeduccion {

    @XmlEnumValue("001")
    VALUE_1("001"),
    @XmlEnumValue("002")
    VALUE_2("002"),
    @XmlEnumValue("003")
    VALUE_3("003"),
    @XmlEnumValue("004")
    VALUE_4("004"),
    @XmlEnumValue("005")
    VALUE_5("005"),
    @XmlEnumValue("006")
    VALUE_6("006"),
    @XmlEnumValue("007")
    VALUE_7("007"),
    @XmlEnumValue("008")
    VALUE_8("008"),
    @XmlEnumValue("009")
    VALUE_9("009"),
    @XmlEnumValue("010")
    VALUE_10("010"),
    @XmlEnumValue("011")
    VALUE_11("011"),
    @XmlEnumValue("012")
    VALUE_12("012"),
    @XmlEnumValue("013")
    VALUE_13("013"),
    @XmlEnumValue("014")
    VALUE_14("014"),
    @XmlEnumValue("015")
    VALUE_15("015"),
    @XmlEnumValue("016")
    VALUE_16("016"),
    @XmlEnumValue("017")
    VALUE_17("017"),
    @XmlEnumValue("018")
    VALUE_18("018"),
    @XmlEnumValue("019")
    VALUE_19("019"),
    @XmlEnumValue("020")
    VALUE_20("020"),
    @XmlEnumValue("021")
    VALUE_21("021"),
    @XmlEnumValue("022")
    VALUE_22("022"),
    @XmlEnumValue("023")
    VALUE_23("023"),
    @XmlEnumValue("024")
    VALUE_24("024"),
    @XmlEnumValue("025")
    VALUE_25("025"),
    @XmlEnumValue("026")
    VALUE_26("026"),
    @XmlEnumValue("027")
    VALUE_27("027"),
    @XmlEnumValue("028")
    VALUE_28("028"),
    @XmlEnumValue("029")
    VALUE_29("029"),
    @XmlEnumValue("030")
    VALUE_30("030"),
    @XmlEnumValue("031")
    VALUE_31("031"),
    @XmlEnumValue("032")
    VALUE_32("032"),
    @XmlEnumValue("033")
    VALUE_33("033"),
    @XmlEnumValue("034")
    VALUE_34("034"),
    @XmlEnumValue("035")
    VALUE_35("035"),
    @XmlEnumValue("036")
    VALUE_36("036"),
    @XmlEnumValue("037")
    VALUE_37("037"),
    @XmlEnumValue("038")
    VALUE_38("038"),
    @XmlEnumValue("039")
    VALUE_39("039"),
    @XmlEnumValue("040")
    VALUE_40("040"),
    @XmlEnumValue("041")
    VALUE_41("041"),
    @XmlEnumValue("042")
    VALUE_42("042"),
    @XmlEnumValue("043")
    VALUE_43("043"),
    @XmlEnumValue("044")
    VALUE_44("044"),
    @XmlEnumValue("045")
    VALUE_45("045"),
    @XmlEnumValue("046")
    VALUE_46("046"),
    @XmlEnumValue("047")
    VALUE_47("047"),
    @XmlEnumValue("048")
    VALUE_48("048"),
    @XmlEnumValue("049")
    VALUE_49("049"),
    @XmlEnumValue("050")
    VALUE_50("050"),
    @XmlEnumValue("051")
    VALUE_51("051"),
    @XmlEnumValue("052")
    VALUE_52("052"),
    @XmlEnumValue("053")
    VALUE_53("053"),
    @XmlEnumValue("054")
    VALUE_54("054"),
    @XmlEnumValue("055")
    VALUE_55("055"),
    @XmlEnumValue("056")
    VALUE_56("056"),
    @XmlEnumValue("057")
    VALUE_57("057"),
    @XmlEnumValue("058")
    VALUE_58("058"),
    @XmlEnumValue("059")
    VALUE_59("059"),
    @XmlEnumValue("060")
    VALUE_60("060"),
    @XmlEnumValue("061")
    VALUE_61("061"),
    @XmlEnumValue("062")
    VALUE_62("062"),
    @XmlEnumValue("063")
    VALUE_63("063"),
    @XmlEnumValue("064")
    VALUE_64("064"),
    @XmlEnumValue("065")
    VALUE_65("065"),
    @XmlEnumValue("066")
    VALUE_66("066"),
    @XmlEnumValue("067")
    VALUE_67("067"),
    @XmlEnumValue("068")
    VALUE_68("068"),
    @XmlEnumValue("069")
    VALUE_69("069"),
    @XmlEnumValue("070")
    VALUE_70("070"),
    @XmlEnumValue("071")
    VALUE_71("071"),
    @XmlEnumValue("072")
    VALUE_72("072"),
    @XmlEnumValue("073")
    VALUE_73("073"),
    @XmlEnumValue("074")
    VALUE_74("074"),
    @XmlEnumValue("075")
    VALUE_75("075"),
    @XmlEnumValue("076")
    VALUE_76("076"),
    @XmlEnumValue("077")
    VALUE_77("077"),
    @XmlEnumValue("078")
    VALUE_78("078"),
    @XmlEnumValue("079")
    VALUE_79("079"),
    @XmlEnumValue("080")
    VALUE_80("080"),
    @XmlEnumValue("081")
    VALUE_81("081"),
    @XmlEnumValue("082")
    VALUE_82("082"),
    @XmlEnumValue("083")
    VALUE_83("083"),
    @XmlEnumValue("084")
    VALUE_84("084"),
    @XmlEnumValue("085")
    VALUE_85("085"),
    @XmlEnumValue("086")
    VALUE_86("086"),
    @XmlEnumValue("087")
    VALUE_87("087"),
    @XmlEnumValue("088")
    VALUE_88("088"),
    @XmlEnumValue("089")
    VALUE_89("089"),
    @XmlEnumValue("090")
    VALUE_90("090"),
    @XmlEnumValue("091")
    VALUE_91("091"),
    @XmlEnumValue("092")
    VALUE_92("092"),
    @XmlEnumValue("093")
    VALUE_93("093"),
    @XmlEnumValue("094")
    VALUE_94("094"),
    @XmlEnumValue("095")
    VALUE_95("095"),
    @XmlEnumValue("096")
    VALUE_96("096"),
    @XmlEnumValue("097")
    VALUE_97("097"),
    @XmlEnumValue("098")
    VALUE_98("098"),
    @XmlEnumValue("099")
    VALUE_99("099"),
    @XmlEnumValue("100")
    VALUE_100("100");
    private final String value;

    C_TipoDeduccion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoDeduccion fromValue(String v) {
        for (C_TipoDeduccion c: C_TipoDeduccion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
