//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoJornada.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoJornada">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoJornada", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoJornada {

	/** 01 - Diurna */
    @XmlEnumValue("02")
    VALUE_1("02"),
    
    /** 02 - Nocturna */
    @XmlEnumValue("03")
    VALUE_2("03"),
    
    /** 03 - Mixta */
    @XmlEnumValue("01")
    VALUE_3("01"),
    
    /** 04 - Por hora */
    @XmlEnumValue("04")
    VALUE_4("04"),
    
    /** 05 - Reducida */
    @XmlEnumValue("05")
    VALUE_5("05"),
    
    /** 06 - Continuada */
    @XmlEnumValue("06")
    VALUE_6("06"),
    
    /** 07 - Partida */
    @XmlEnumValue("07")
    VALUE_7("07"),
    
    /** 08 - Por turnos */
    @XmlEnumValue("08")
    VALUE_8("08"),
    
    /** 99 - Otra Jornada */
    @XmlEnumValue("99")
    VALUE_9("99");
    
    private final String value;

    C_TipoJornada(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoJornada fromValue(String v) {
        for (C_TipoJornada c: C_TipoJornada.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
