//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for c_TipoIncapacidad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoIncapacidad">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoIncapacidad", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum C_TipoIncapacidad {

	/** 01 - Riesgo de trabajo*/
    @XmlEnumValue("01")
    VALUE_1("01"),
    
    /** 02 - Enfermedad en general */
    @XmlEnumValue("02")
    VALUE_2("02"),
    
    /** 03 - Maternidad */
    @XmlEnumValue("03")
    VALUE_3("03");
    private final String value;

    C_TipoIncapacidad(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TipoIncapacidad fromValue(String v) {
        for (C_TipoIncapacidad c: C_TipoIncapacidad.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
