//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.nomina;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.gob.sat.sitio_internet.cfd.catalogos.nomina package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.gob.sat.sitio_internet.cfd.catalogos.nomina
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NominaElement }
     * 
     */
    public NominaElement createNominaElement() {
        return new NominaElement();
    }

    /**
     * Create an instance of {@link NominaElement.Incapacidades }
     * 
     */
    public NominaElement.Incapacidades createNominaElementIncapacidades() {
        return new NominaElement.Incapacidades();
    }

    /**
     * Create an instance of {@link NominaElement.OtrosPagos }
     * 
     */
    public NominaElement.OtrosPagos createNominaElementOtrosPagos() {
        return new NominaElement.OtrosPagos();
    }

    /**
     * Create an instance of {@link NominaElement.OtrosPagos.OtroPago }
     * 
     */
    public NominaElement.OtrosPagos.OtroPago createNominaElementOtrosPagosOtroPago() {
        return new NominaElement.OtrosPagos.OtroPago();
    }

    /**
     * Create an instance of {@link NominaElement.Deducciones }
     * 
     */
    public NominaElement.Deducciones createNominaElementDeducciones() {
        return new NominaElement.Deducciones();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones }
     * 
     */
    public NominaElement.Percepciones createNominaElementPercepciones() {
        return new NominaElement.Percepciones();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones.Percepcion }
     * 
     */
    public NominaElement.Percepciones.Percepcion createNominaElementPercepcionesPercepcion() {
        return new NominaElement.Percepciones.Percepcion();
    }

    /**
     * Create an instance of {@link NominaElement.Receptor }
     * 
     */
    public NominaElement.Receptor createNominaElementReceptor() {
        return new NominaElement.Receptor();
    }

    /**
     * Create an instance of {@link NominaElement.Emisor }
     * 
     */
    public NominaElement.Emisor createNominaElementEmisor() {
        return new NominaElement.Emisor();
    }

    /**
     * Create an instance of {@link NominaElement.Incapacidades.Incapacidad }
     * 
     */
    public NominaElement.Incapacidades.Incapacidad createNominaElementIncapacidadesIncapacidad() {
        return new NominaElement.Incapacidades.Incapacidad();
    }

    /**
     * Create an instance of {@link NominaElement.OtrosPagos.OtroPago.SubsidioAlEmpleo }
     * 
     */
    public NominaElement.OtrosPagos.OtroPago.SubsidioAlEmpleo createNominaElementOtrosPagosOtroPagoSubsidioAlEmpleo() {
        return new NominaElement.OtrosPagos.OtroPago.SubsidioAlEmpleo();
    }

    /**
     * Create an instance of {@link NominaElement.OtrosPagos.OtroPago.CompensacionSaldosAFavor }
     * 
     */
    public NominaElement.OtrosPagos.OtroPago.CompensacionSaldosAFavor createNominaElementOtrosPagosOtroPagoCompensacionSaldosAFavor() {
        return new NominaElement.OtrosPagos.OtroPago.CompensacionSaldosAFavor();
    }

    /**
     * Create an instance of {@link NominaElement.Deducciones.Deduccion }
     * 
     */
    public NominaElement.Deducciones.Deduccion createNominaElementDeduccionesDeduccion() {
        return new NominaElement.Deducciones.Deduccion();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones.JubilacionPensionRetiro }
     * 
     */
    public NominaElement.Percepciones.JubilacionPensionRetiro createNominaElementPercepcionesJubilacionPensionRetiro() {
        return new NominaElement.Percepciones.JubilacionPensionRetiro();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones.SeparacionIndemnizacion }
     * 
     */
    public NominaElement.Percepciones.SeparacionIndemnizacion createNominaElementPercepcionesSeparacionIndemnizacion() {
        return new NominaElement.Percepciones.SeparacionIndemnizacion();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones.Percepcion.AccionesOTitulos }
     * 
     */
    public NominaElement.Percepciones.Percepcion.AccionesOTitulos createNominaElementPercepcionesPercepcionAccionesOTitulos() {
        return new NominaElement.Percepciones.Percepcion.AccionesOTitulos();
    }

    /**
     * Create an instance of {@link NominaElement.Percepciones.Percepcion.HorasExtra }
     * 
     */
    public NominaElement.Percepciones.Percepcion.HorasExtra createNominaElementPercepcionesPercepcionHorasExtra() {
        return new NominaElement.Percepciones.Percepcion.HorasExtra();
    }

    /**
     * Create an instance of {@link NominaElement.Receptor.SubContratacion }
     * 
     */
    public NominaElement.Receptor.SubContratacion createNominaElementReceptorSubContratacion() {
        return new NominaElement.Receptor.SubContratacion();
    }

    /**
     * Create an instance of {@link NominaElement.Emisor.EntidadSNCF }
     * 
     */
    public NominaElement.Emisor.EntidadSNCF createNominaElementEmisorEntidadSNCF() {
        return new NominaElement.Emisor.EntidadSNCF();
    }

}
