//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/nomina12",
	xmlns = {
			@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/nomina12", prefix="nomina12")
	}
	,elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tikal.cacao.sat.cfd.nomina;
