
package com.finkok.facturacion.stamp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2018-05-31T12:13:20.089-05:00
 * Generated source version: 3.1.15
 * 
 */
public final class Application_Application_Client {

    private static final QName SERVICE_NAME = new QName("http://facturacion.finkok.com/stamp", "StampSOAP");

    private Application_Application_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StampSOAP.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StampSOAP ss = new StampSOAP(wsdlURL, SERVICE_NAME);
        Application port = ss.getApplication();  
        
        {
        System.out.println("Invoking queryPending...");
        java.lang.String _queryPending_username = "_queryPending_username423179837";
        java.lang.String _queryPending_password = "_queryPending_password-544428335";
        java.lang.String _queryPending_uuid = "_queryPending_uuid-2047681276";
        views.core.soap.services.apps.QueryPendingResult _queryPending__return = port.queryPending(_queryPending_username, _queryPending_password, _queryPending_uuid);
        System.out.println("queryPending.result=" + _queryPending__return);


        }
        {
        System.out.println("Invoking stamp...");
        byte[] _stamp_xml = new byte[] {};
        java.lang.String _stamp_username = "_stamp_username-378305335";
        java.lang.String _stamp_password = "_stamp_password-1255765572";
        views.core.soap.services.apps.AcuseRecepcionCFDI _stamp__return = port.stamp(_stamp_xml, _stamp_username, _stamp_password);
        System.out.println("stamp.result=" + _stamp__return);


        }
        {
        System.out.println("Invoking signStamp...");
        byte[] _signStamp_xml = new byte[] {};
        java.lang.String _signStamp_username = "_signStamp_username-1975787452";
        java.lang.String _signStamp_password = "_signStamp_password-438078926";
        views.core.soap.services.apps.AcuseRecepcionCFDI _signStamp__return = port.signStamp(_signStamp_xml, _signStamp_username, _signStamp_password);
        System.out.println("signStamp.result=" + _signStamp__return);


        }
        {
        System.out.println("Invoking quickStamp...");
        byte[] _quickStamp_xml = new byte[] {};
        java.lang.String _quickStamp_username = "_quickStamp_username1194820661";
        java.lang.String _quickStamp_password = "_quickStamp_password-1643241491";
        views.core.soap.services.apps.AcuseRecepcionCFDI _quickStamp__return = port.quickStamp(_quickStamp_xml, _quickStamp_username, _quickStamp_password);
        System.out.println("quickStamp.result=" + _quickStamp__return);


        }
        {
        System.out.println("Invoking getPdf...");
        java.lang.String _getPdf_username = "_getPdf_username1600493910";
        java.lang.String _getPdf_password = "_getPdf_password103100774";
        java.lang.String _getPdf_uuid = "_getPdf_uuid-20622584";
        views.core.soap.services.apps.PDFResult _getPdf__return = port.getPdf(_getPdf_username, _getPdf_password, _getPdf_uuid);
        System.out.println("getPdf.result=" + _getPdf__return);


        }
        {
        System.out.println("Invoking stamped...");
        byte[] _stamped_xml = new byte[] {};
        java.lang.String _stamped_username = "_stamped_username-2109943678";
        java.lang.String _stamped_password = "_stamped_password515385044";
        views.core.soap.services.apps.AcuseRecepcionCFDI _stamped__return = port.stamped(_stamped_xml, _stamped_username, _stamped_password);
        System.out.println("stamped.result=" + _stamped__return);


        }

        System.exit(0);
    }

}
