//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>Java class for c_FormaPago.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_FormaPago">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="12"/>
 *     &lt;enumeration value="13"/>
 *     &lt;enumeration value="14"/>
 *     &lt;enumeration value="15"/>
 *     &lt;enumeration value="17"/>
 *     &lt;enumeration value="23"/>
 *     &lt;enumeration value="24"/>
 *     &lt;enumeration value="25"/>
 *     &lt;enumeration value="26"/>
 *     &lt;enumeration value="27"/>
 *     &lt;enumeration value="28"/>
 *     &lt;enumeration value="29"/>
 *     &lt;enumeration value="99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_FormaPago", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_FormaPago {
	/** 01 - Efectivo*/
	@SerializedName("Efectivo")
    @XmlEnumValue("01")
    VALUE_1("01"),
    
    /** 02 - Cheque nominativo*/
    @SerializedName("Cheque nominativo")
    @XmlEnumValue("02")
    VALUE_2("02"),
    
    /** 03 - Transferencia electr&oacute;nica de fondos */
    @SerializedName("Transferencia electr�nica de fondos")
    @XmlEnumValue("03")
    VALUE_3("03"),
    
    /** 04 - Tarjeta de cr&eacute;dito */
    @SerializedName("Tarjeta de cr�dito")
    @XmlEnumValue("04")
    VALUE_4("04"),
    
    /** 05 - Monedero electr&oacute;nico */
    @SerializedName("Monedero electr�nico")
    @XmlEnumValue("05")
    VALUE_5("05"),
    
    /** 06 - Dinero electr&oacute;nico */
    @SerializedName("Dinero electr�nico")
    @XmlEnumValue("06")
    VALUE_6("06"),
    
    /** 08 - Vales de despensa */
    @SerializedName("Vales de despensa")
    @XmlEnumValue("08")
    VALUE_7("08"),
    
    /** 12 - Daci&oacute;n en pago*/
    @SerializedName("Daci�n en pago")
    @XmlEnumValue("12")
    VALUE_8("12"),
    
    /** 13 - Pago por subrogaci&oacute;n*/
    @SerializedName("Pago por subrogaci�n")
    @XmlEnumValue("13")
    VALUE_9("13"),
    
    /** 14 - Pago por consignaci&oacute;n */
    @SerializedName("Pago por consignaci�n")
    @XmlEnumValue("14")
    VALUE_10("14"),
    
    /** 15 - Condonaci&oacute;n */
    @SerializedName("Condonaci�n")
    @XmlEnumValue("15")
    VALUE_11("15"),
    
    /** 17 - Compensaci&oacute;n */
    @SerializedName("Compensaci�n")
    @XmlEnumValue("17")
    VALUE_12("17"),
    
    /** 23 - Novaci&oacute;n */
    @SerializedName("Novaci�n")
    @XmlEnumValue("23")
    VALUE_13("23"),
    
    /** 24 - Confusi&oacute;n */
    @SerializedName("Confusi�n")
    @XmlEnumValue("24")
    VALUE_14("24"),
    
    /** 25 - Remisi&oacute;n de deuda*/
    @SerializedName("Remisi�n de deuda")
    @XmlEnumValue("25")
    VALUE_15("25"),
    
    /** 26 - Prescripci&oacute;n o caducidad*/
    @SerializedName("Prescripci�n o caducidad")
    @XmlEnumValue("26")
    VALUE_16("26"),
    
    /** 27 - A satisfacci&oacute;n del acreedor */
    @SerializedName("A satisfacci�n del acreedor")
    @XmlEnumValue("27")
    VALUE_17("27"),
    
    /** 28 - Tarjeta de d&eacute;bito*/
    @SerializedName("Tarjeta de d�bito")
    @XmlEnumValue("28")
    VALUE_18("28"),
    
    /** 29 - Tarjeta de servicios*/
    @SerializedName("Tarjeta de servicios")
    @XmlEnumValue("29")
    VALUE_19("29"),
    
    /** 99 - Por definir */
    @SerializedName("Por definir")
    @XmlEnumValue("99")
    VALUE_20("99");
    private final String value;

    C_FormaPago(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_FormaPago fromValue(String v) {
        for (C_FormaPago c: C_FormaPago.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
