//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 05:42:21 PM CST 
//

package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;


/**
 * <p>Java class for c_RegimenFiscal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_RegimenFiscal">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="601"/>
 *     &lt;enumeration value="603"/>
 *     &lt;enumeration value="605"/>
 *     &lt;enumeration value="606"/>
 *     &lt;enumeration value="608"/>
 *     &lt;enumeration value="609"/>
 *     &lt;enumeration value="610"/>
 *     &lt;enumeration value="611"/>
 *     &lt;enumeration value="612"/>
 *     &lt;enumeration value="614"/>
 *     &lt;enumeration value="616"/>
 *     &lt;enumeration value="620"/>
 *     &lt;enumeration value="621"/>
 *     &lt;enumeration value="622"/>
 *     &lt;enumeration value="623"/>
 *     &lt;enumeration value="624"/>
 *     &lt;enumeration value="628"/>
 *     &lt;enumeration value="607"/>
 *     &lt;enumeration value="629"/>
 *     &lt;enumeration value="630"/>
 *     &lt;enumeration value="615"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_RegimenFiscal", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_RegimenFiscal {

	/** 601 - General de Ley Personas Morales */
	@SerializedName("General de Ley Personas Morales")
    @XmlEnumValue("601")
    VALUE_1("601"),

	/** 603 - Personas Morales con Fines no Lucrativos */
    @SerializedName("Personas Morales con Fines no Lucrativos")
    @XmlEnumValue("603")
    VALUE_2("603"),

	/** 605 - Sueldos y Salarios e Ingresos Asimilados a Salarios */
    @SerializedName("Sueldos y Salarios e Ingresos Asimilados a Salarios")
    @XmlEnumValue("605")
    VALUE_3("605"),

	/** 606 - Arrendamiento */
    @SerializedName("Arrendamiento")
    @XmlEnumValue("606")
    VALUE_4("606"),

	/** 608 - Dem&aacute;s ingresos */
    @SerializedName("Dem�s ingresos")
	@XmlEnumValue("608")
    VALUE_5("608"),

	/** 609 - Consolidaci&oacute;n */
    @SerializedName("Consolidaci�n")
	@XmlEnumValue("609")
    VALUE_6("609"),

	/** 610 - Residentes en el Extranjero sin Establecimiento Permanente en M&eacute;xico */
    @SerializedName("Residentes en el Extranjero sin Establecimiento Permanente en M�xico")
	@XmlEnumValue("610")
    VALUE_7("610"),

	/** 611 - Ingresos por Dividendos (socios y accionistas) */
    @SerializedName("Ingresos por Dividendos (socios y accionistas)")
	@XmlEnumValue("611")
    VALUE_8("611"),

	/** 612 - Personas F&iacute;sicas con Actividades Empresariales y Profesionales */
    @SerializedName("Personas F�sicas con Actividades Empresariales y Profesionales")
	@XmlEnumValue("612")
    VALUE_9("612"),

	/** 614 - Ingresos por intereses */
    @SerializedName("Ingresos por intereses")
	@XmlEnumValue("614")
    VALUE_10("614"),

	/** 616 - Sin obligaciones fiscales */
    @SerializedName("Sin obligaciones fiscales")
	@XmlEnumValue("616")
    VALUE_11("616"),

	/** 620 - Sociedades Cooperativas de Producci&oacute;n que optan por diferir sus ingresos */
    @SerializedName("Sociedades Cooperativas de Producci�n que optan por diferir sus ingresos")
	@XmlEnumValue("620")
    VALUE_12("620"),

	/** 621 - Incorporaci&oacute;n Fiscal */
    @SerializedName("Incorporaci�n Fiscal")
	@XmlEnumValue("621")
    VALUE_13("621"),

	/** 622 - Actividades Agr&iacute;colas, Ganaderas, Silv&iacute;colas y Pesqueras */
    @SerializedName("Actividades Agr�colas, Ganaderas, Silv�colas y Pesqueras")
	@XmlEnumValue("622")
    VALUE_14("622"),

	/** 623 - Opcional para Grupos de Sociedades */
    @SerializedName("Opcional para Grupos de Sociedades")
	@XmlEnumValue("623")
    VALUE_15("623"),

	/** 624 - Coordinados */
    @SerializedName("Coordinados")
	@XmlEnumValue("624")
    VALUE_16("624"),

	/** 628 - Hidrocarburos */
    @SerializedName("Hidrocarburos")
	@XmlEnumValue("628")
    VALUE_17("628"),

	/** 607 - R&eacute;gimen de Enajenaci&oacute;n o Adquisici&oacute;n de Bienes */
    @SerializedName("R�gimen de Enajenaci�n o Adquisici�n de Bienes")
	@XmlEnumValue("607")
    VALUE_18("607"),

	/** 629 - De los Reg&iacute;menes Fiscales Preferentes y de las Empresas Multinacionales */
    @SerializedName("De los Reg�menes Fiscales Preferentes y de las Empresas Multinacionales")
	@XmlEnumValue("629")
    VALUE_19("629"),

	/** 630 - Enajenaci&oacute;n de acciones en bolsa de valores */
    @SerializedName("Enajenaci�n de acciones en bolsa de valores")
	@XmlEnumValue("630")
    VALUE_20("630"),

	/** 615 - R&eacute;gimen de los ingresos por obtenci&oacute;n de premios */
    @SerializedName("R�gimen de los ingresos por obtenci�n de premios")
	@XmlEnumValue("615")
    VALUE_21("615");
    
    private final String value;

    C_RegimenFiscal(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_RegimenFiscal fromValue(String v) {
        for (C_RegimenFiscal c: C_RegimenFiscal.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
