//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.24 at 10:04:15 AM CST 
//

package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TasaOCuota.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TasaOCuota">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="0.000000"/>
 *     &lt;enumeration value="0.160000"/>
 *     &lt;enumeration value="0.265000"/>
 *     &lt;enumeration value="0.300000"/>
 *     &lt;enumeration value="0.530000"/>
 *     &lt;enumeration value="0.500000"/>
 *     &lt;enumeration value="1.600000"/>
 *     &lt;enumeration value="0.304000"/>
 *     &lt;enumeration value="0.350000"/>
 *     &lt;enumeration value="0.059100"/>
 *     &lt;enumeration value="3.000000"/>
 *     &lt;enumeration value="0.298800"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TasaOCuota", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_TasaOCuota {

    @XmlEnumValue("0.000000")
    VALUE_1("0.000000"),
    @XmlEnumValue("0.160000")
    VALUE_2("0.160000"),
    @XmlEnumValue("0.265000")
    VALUE_3("0.265000"),
    @XmlEnumValue("0.300000")
    VALUE_4("0.300000"),
    @XmlEnumValue("0.530000")
    VALUE_5("0.530000"),
    @XmlEnumValue("0.500000")
    VALUE_6("0.500000"),
    @XmlEnumValue("1.600000")
    VALUE_7("1.600000"),
    @XmlEnumValue("0.304000")
    VALUE_8("0.304000"),
    @XmlEnumValue("0.350000")
    VALUE_9("0.350000"),
    @XmlEnumValue("0.059100")
    VALUE_10("0.059100"),
    @XmlEnumValue("3.000000")
    VALUE_11("3.000000"),
    @XmlEnumValue("0.298800")
    VALUE_12("0.298800");
    private final String value;

    C_TasaOCuota(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_TasaOCuota fromValue(String v) {
        for (C_TasaOCuota c: C_TasaOCuota.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
