//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.24 at 10:04:15 AM CST 
//

package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_UsoCFDI.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_UsoCFDI">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="G01"/>
 *     &lt;enumeration value="G02"/>
 *     &lt;enumeration value="G03"/>
 *     &lt;enumeration value="I01"/>
 *     &lt;enumeration value="I02"/>
 *     &lt;enumeration value="I03"/>
 *     &lt;enumeration value="I04"/>
 *     &lt;enumeration value="I05"/>
 *     &lt;enumeration value="I06"/>
 *     &lt;enumeration value="I07"/>
 *     &lt;enumeration value="I08"/>
 *     &lt;enumeration value="D01"/>
 *     &lt;enumeration value="D02"/>
 *     &lt;enumeration value="D03"/>
 *     &lt;enumeration value="D04"/>
 *     &lt;enumeration value="D05"/>
 *     &lt;enumeration value="D06"/>
 *     &lt;enumeration value="D07"/>
 *     &lt;enumeration value="D08"/>
 *     &lt;enumeration value="D09"/>
 *     &lt;enumeration value="D10"/>
 *     &lt;enumeration value="P01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_UsoCFDI", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_UsoCFDI {

	/** G01 - Adquisici&oacute;n de mercancias*/
    @XmlEnumValue("G01")
    G_01("G01"),
    
    /** G02- Devoluciones, descuentos o bonificaciones */
    @XmlEnumValue("G02")
    G_02("G02"),
    
    /** G03 - Gastos en general*/
    @XmlEnumValue("G03")
    G_03("G03"),
    
    /** I01 - Construcciones*/
    @XmlEnumValue("I01")
    I_01("I01"),
    
    /** I02 - Mobilario y equipo de oficina por inversiones*/
    @XmlEnumValue("I02")
    I_02("I02"),
    
    /** I03 - Equipo de transporte*/
    @XmlEnumValue("I03")
    I_03("I03"),
    
    /** I04 - Equipo de computo y accesorios*/
    @XmlEnumValue("I04")
    I_04("I04"),
    
    /** I05 - Dados, troqueles, moldes, matrices y herramental*/
    @XmlEnumValue("I05")
    I_05("I05"),
    
    /** I06 - Comunicaciones telef&oacute;nicas*/
    @XmlEnumValue("I06")
    I_06("I06"),
    
    /** I07 - Comunicaciones satelitales*/
    @XmlEnumValue("I07")
    I_07("I07"),
    
    /** I08 - Otra maquinaria y equipo*/
    @XmlEnumValue("I08")
    I_08("I08"),
    
    /** D01 - Honorarios m&eacute;dicos, dentales y gastos hospitalarios.*/
    @XmlEnumValue("D01")
    D_01("D01"),
    
    /** D02 - Gastos m&eacute;dicos por incapacidad o discapacidad*/
    @XmlEnumValue("D02")
    D_02("D02"),
    
    /** D03 - Gastos funerales.*/
    @XmlEnumValue("D03")
    D_03("D03"),
    
    /** D04 - Donativos.*/
    @XmlEnumValue("D04")
    D_04("D04"),
    
    /** D05 - Intereses reales efectivamente pagados por cr&eacute;ditos hipotecarios (casa habitaci&oacute;n).*/
    @XmlEnumValue("D05")
    D_05("D05"),
    
    /** D06 - Aportaciones voluntarias al SAR.*/
    @XmlEnumValue("D06")
    D_06("D06"),
    
    /** D07 - Primas por seguros de gastos m&eacute;dicos. */
    @XmlEnumValue("D07")
    D_07("D07"),
    
    /** D08 - Gastos de transportaci&oacute;n escolar obligatoria */
    @XmlEnumValue("D08")
    D_08("D08"),
    
    /** D09 - Dep&oacute;sitos en cuentas para el ahorro, primas que tengan como base planes de pensiones */
    @XmlEnumValue("D09")
    D_09("D09"),
    
    /** D10 - Pagos por servicios educativos (colegiaturas) */
    @XmlEnumValue("D10")
    D_10("D10"),
    
    /** P01 - Por definir*/
    @XmlEnumValue("P01")
    P_01("P01");
    
    private final String value;

    C_UsoCFDI(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_UsoCFDI fromValue(String v) {
        for (C_UsoCFDI c: C_UsoCFDI.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
