
package localhost;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Timbrado", targetNamespace = "http://localhost/", wsdlLocation = "http://201.175.12.89/serviciointegracionpruebas/Timbrado.asmx?wsdl")
public class Timbrado
    extends Service
{

    private final static URL TIMBRADO_WSDL_LOCATION;
    private final static WebServiceException TIMBRADO_EXCEPTION;
    private final static QName TIMBRADO_QNAME = new QName("http://localhost/", "Timbrado");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.175.12.89/serviciointegracionpruebas/Timbrado.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMBRADO_WSDL_LOCATION = url;
        TIMBRADO_EXCEPTION = e;
    }

    public Timbrado() {
        super(__getWsdlLocation(), TIMBRADO_QNAME);
    }

    public Timbrado(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMBRADO_QNAME, features);
    }

    public Timbrado(URL wsdlLocation) {
        super(wsdlLocation, TIMBRADO_QNAME);
    }

    public Timbrado(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMBRADO_QNAME, features);
    }

    public Timbrado(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Timbrado(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimbradoSoap
     */
    @WebEndpoint(name = "TimbradoSoap")
    public TimbradoSoap getTimbradoSoap() {
        return super.getPort(new QName("http://localhost/", "TimbradoSoap"), TimbradoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimbradoSoap
     */
    @WebEndpoint(name = "TimbradoSoap")
    public TimbradoSoap getTimbradoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/", "TimbradoSoap"), TimbradoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMBRADO_EXCEPTION!= null) {
            throw TIMBRADO_EXCEPTION;
        }
        return TIMBRADO_WSDL_LOCATION;
    }

}
