
package localhost;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimbradoSoap", targetNamespace = "http://localhost/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimbradoSoap {

    /**
     * Servicio de registro para emisores
     * 
     * @param usuarioIntegrador
     * @param contrasena
     * @param base64Key
     * @param base64Cer
     * @param rfcEmisor
     * @return
     *     returns localhost.ArrayOfAnyType
     */
    @WebMethod(operationName = "RegistraEmisor", action = "http://localhost/RegistraEmisor")
    @WebResult(name = "RegistraEmisorResult", targetNamespace = "http://localhost/")
    @RequestWrapper(localName = "RegistraEmisor", targetNamespace = "http://localhost/", className = "localhost.RegistraEmisor")
    @ResponseWrapper(localName = "RegistraEmisorResponse", targetNamespace = "http://localhost/", className = "localhost.RegistraEmisorResponse")
    public ArrayOfAnyType registraEmisor(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://localhost/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://localhost/")
        String rfcEmisor,
        @WebParam(name = "base64Cer", targetNamespace = "http://localhost/")
        String base64Cer,
        @WebParam(name = "base64Key", targetNamespace = "http://localhost/")
        String base64Key,
        @WebParam(name = "contrasena", targetNamespace = "http://localhost/")
        String contrasena);

    /**
     * Servicio de timbrado para Integradores
     * 
     * @param usuarioIntegrador
     * @param xmlComprobanteBase64
     * @param idComprobante
     * @return
     *     returns localhost.ArrayOfAnyType
     */
    @WebMethod(operationName = "TimbraCFDI", action = "http://localhost/TimbraCFDI")
    @WebResult(name = "TimbraCFDIResult", targetNamespace = "http://localhost/")
    @RequestWrapper(localName = "TimbraCFDI", targetNamespace = "http://localhost/", className = "localhost.TimbraCFDI")
    @ResponseWrapper(localName = "TimbraCFDIResponse", targetNamespace = "http://localhost/", className = "localhost.TimbraCFDIResponse")
    public ArrayOfAnyType timbraCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://localhost/")
        String usuarioIntegrador,
        @WebParam(name = "xmlComprobanteBase64", targetNamespace = "http://localhost/")
        String xmlComprobanteBase64,
        @WebParam(name = "idComprobante", targetNamespace = "http://localhost/")
        String idComprobante);

    /**
     * Servicio de cancelaci�n CFDI
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns localhost.ArrayOfAnyType
     */
    @WebMethod(operationName = "CancelaCFDI", action = "http://localhost/CancelaCFDI")
    @WebResult(name = "CancelaCFDIResult", targetNamespace = "http://localhost/")
    @RequestWrapper(localName = "CancelaCFDI", targetNamespace = "http://localhost/", className = "localhost.CancelaCFDI")
    @ResponseWrapper(localName = "CancelaCFDIResponse", targetNamespace = "http://localhost/", className = "localhost.CancelaCFDIResponse")
    public ArrayOfAnyType cancelaCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://localhost/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://localhost/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://localhost/")
        String folioUUID);

    /**
     * Servicio de consulta CFDI
     * 
     * @param usuarioIntegrador
     * @param folioUUID
     * @param rfcEmisor
     * @return
     *     returns localhost.ArrayOfAnyType
     */
    @WebMethod(operationName = "ObtieneCFDI", action = "http://localhost/ObtieneCFDI")
    @WebResult(name = "ObtieneCFDIResult", targetNamespace = "http://localhost/")
    @RequestWrapper(localName = "ObtieneCFDI", targetNamespace = "http://localhost/", className = "localhost.ObtieneCFDI")
    @ResponseWrapper(localName = "ObtieneCFDIResponse", targetNamespace = "http://localhost/", className = "localhost.ObtieneCFDIResponse")
    public ArrayOfAnyType obtieneCFDI(
        @WebParam(name = "usuarioIntegrador", targetNamespace = "http://localhost/")
        String usuarioIntegrador,
        @WebParam(name = "rfcEmisor", targetNamespace = "http://localhost/")
        String rfcEmisor,
        @WebParam(name = "folioUUID", targetNamespace = "http://localhost/")
        String folioUUID);

}
