//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 10:36:28 AM CST 

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/Pagos",
xmlns = {
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/Pagos", prefix="pago10")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.gob.sat.pagos;
