//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.26 at 01:28:39 PM CDT 

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/TimbreFiscalDigital")
package com.tikal.cacao.sat.timbrefiscaldigital;
